#!/bin/bash
# RENDER ADMIN SETUP - Automated configuration helper
# This script helps you configure the admin panel on your Render deployment

echo "=========================================="
echo "PeakeBot Admin Panel - Render Setup"
echo "=========================================="
echo ""
echo "Your service is live at:"
echo "  https://peake-ai.onrender.com"
echo ""
echo "To complete admin panel setup:"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Find service: 'peake-ai'"
echo "3. Click the 'Environment' tab"
echo "4. Click 'Add Environment Variable'"
echo ""
echo "5a. First variable:"
echo "    Key:   ADMIN_PANEL_ENABLED"
echo "    Value: true"
echo "    Click 'Save'"
echo ""
echo "5b. Second variable:"
echo "    Key:   ADMIN_API_KEY"
echo "    Value: admin-secret-$(date +%s)"
echo "    (Or use any strong string you prefer)"
echo "    Click 'Save'"
echo ""
echo "6. Wait 1-2 minutes for Render to redeploy"
echo ""
echo "7. Visit: https://peake-ai.onrender.com/admin"
echo ""
echo "8. Enter the ADMIN_API_KEY value you set in step 5b"
echo ""
echo "=========================================="
echo "✅ System is live and ready for configuration"
echo "=========================================="
