# config.py
# Tunable game settings


MOUSE_SENSITIVITY = 0.2
PLAYER_SPEED = 8.0
PLAYER_SPRINT_MULT = 1.6
PLAYER_JUMP_FORCE = 13.0
PLAYER_GRAVITY = -32.0
PLAYER_HEALTH = 100
PLAYER_HEADBOB_FREQ = 8.0
PLAYER_HEADBOB_MAG = 0.08
PLAYER_FOV = 75
PLAYER_FOV_SPRINT = 85
PLAYER_DASH_TIME = 0.18
PLAYER_DASH_COOLDOWN = 0.7

# Camera/player spawn height tuning
PLAYER_SPAWN_HEIGHT = 1.2
PLAYER_CAMERA_HEIGHT = 0.7

WEAPON_RECOIL = {
    "Pistol": 2.0,
    "Shotgun": 5.0,
    "Rifle": 1.2,
}

ENEMY_SPEED = 3.0
ENEMY_HEALTH = 40

LEVEL_SIZE = 32
